### ISSUE TITLE
mac  os  

### ISSUE THREAD

**Issue by OSMeteor** [vcaesar/robotn#1]
/Users/osmeteor/node_modules/_ffi@2.3.0@ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
    ^

Error: Dynamic Linking Error: dlopen(/Users/osmeteor/node_modules/_robotn@0.10.0@robotn/robotgo.dylib, 2): image not found
    at new DynamicLibrary (/Users/osmeteor/node_modules/_ffi@2.3.0@ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/Users/osmeteor/node_modules/_ffi@2.3.0@ffi/lib/library.js:45:12)
    at Object.<anonymous> (/Users/osmeteor/node_modules/_robotn@0.10.0@robotn/robot.js:54:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by vcaesar** [comment]
Now, there is no prebuild binary version available, you need to install dependencies ( go and gcc ), https://github.com/go-vgo/robotgo#requirements.
